import React, {useEffect, useRef} from 'react';
import {Animated, Image, StyleSheet, Text, TouchableOpacity, View} from 'react-native';
import Clipboard from '@react-native-clipboard/clipboard';
import {useTranslation} from 'react-i18next';
import {radius, spacing} from '../theme';
import {useTheme} from '../theme/ThemeContext';
import {ChatMessage} from '../types';
import {TypingIndicator} from './TypingIndicator';
import {MarkdownText} from './MarkdownText';
import {AssistantAvatarIcon, CopyIcon, RegenerateIcon, EditIcon, ThumbsDownIcon, ThumbsUpIcon} from './Icons';

/** A slim blinking bar appended after the growing streamed text -- the only
 * animation here, and it's opacity-only on a fixed-size element so it stays
 * cheap on low-end devices (useNativeDriver, no layout/re-measure work on
 * every blink). */
function StreamingCursor() {
  const {colors} = useTheme();
  const opacity = useRef(new Animated.Value(1)).current;

  useEffect(() => {
    const loop = Animated.loop(
      Animated.sequence([
        Animated.timing(opacity, {toValue: 0, duration: 500, useNativeDriver: true}),
        Animated.timing(opacity, {toValue: 1, duration: 500, useNativeDriver: true}),
      ]),
    );
    loop.start();
    return () => loop.stop();
  }, [opacity]);

  return (
    <Animated.View style={[styles.cursor, {backgroundColor: colors.textPrimary, opacity}]} />
  );
}

export function ChatBubble({
  message,
  isStreaming,
  modelName,
  avatarIconId,
  onRegenerate,
  onEdit,
  onFeedback,
}: {
  message: ChatMessage;
  isStreaming?: boolean;
  /** Only meaningful for assistant messages -- the small "generated by"
   * indicator above the reply. */
  modelName?: string;
  avatarIconId?: string;
  /** Only passed for the last assistant message. */
  onRegenerate?: () => void;
  /** Only passed for the last user message. */
  onEdit?: () => void;
  /** Any assistant message can be rated, not just the last one. */
  onFeedback?: (feedback: 'up' | 'down') => void;
}) {
  const isUser = message.role === 'user';
  const showActions = !isStreaming && (isUser ? !!onEdit : true);
  // While waiting for the first token, show the wave instead of an empty
  // bubble; once text starts arriving, a blinking cursor after the growing
  // text communicates "still generating" without a busy/looping indicator
  // competing with the text itself for attention.
  const waitingForFirstToken = isStreaming && message.content.length === 0;
  const showCursor = isStreaming && message.content.length > 0;
  const {colors, typography} = useTheme();
  const {t} = useTranslation();

  return (
    <View
      style={[
        styles.row,
        {justifyContent: isUser ? 'flex-end' : 'flex-start'},
      ]}>
      <View style={isUser ? styles.userMaxWidth : styles.assistantMaxWidth}>
        {!isUser && (
          <View style={styles.aiHeader}>
            <View style={[styles.aiAvatar, {backgroundColor: colors.surfaceContainerHigh}]}>
              <AssistantAvatarIcon
                id={avatarIconId ?? 'bot'}
                size={12}
                color={colors.textSecondary}
              />
            </View>
            <Text style={[typography.small, {color: colors.textMuted}]} numberOfLines={1}>
              {modelName ?? 'Assistant'}
            </Text>
          </View>
        )}

        <View
          style={[
            styles.bubble,
            {backgroundColor: isUser ? colors.userBubble : colors.assistantBubble},
            isUser ? styles.userBubbleCorner : styles.assistantBubblePadding,
          ]}>
          {message.imagePath && (
            <Image
              source={{uri: `file://${message.imagePath}`}}
              style={[styles.image, {backgroundColor: colors.surfaceContainerHigh}]}
              resizeMode="cover"
            />
          )}
          {waitingForFirstToken ? (
            <TypingIndicator />
          ) : isUser ? (
            <Text style={[styles.userText, {color: colors.textPrimary}]}>{message.content}</Text>
          ) : (
            <View style={styles.markdownRow}>
              <View style={styles.markdownContent}>
                <MarkdownText content={message.content} color={colors.textPrimary} />
              </View>
              {showCursor && <StreamingCursor />}
            </View>
          )}
        </View>

        {showActions && (
          <View
            style={[
              styles.actions,
              {justifyContent: isUser ? 'flex-end' : 'space-between'},
            ]}>
            <View style={styles.actionsLeft}>
              {!isUser && (
                <TouchableOpacity
                  style={styles.actionButton}
                  onPress={() => Clipboard.setString(message.content)}
                  hitSlop={6}>
                  <CopyIcon color={colors.textSecondary} />
                  <Text style={[styles.actionLabel, {color: colors.textSecondary}]}>{t('chat.copy')}</Text>
                </TouchableOpacity>
              )}
              {!isUser && onRegenerate && (
                <TouchableOpacity style={styles.actionButton} onPress={onRegenerate} hitSlop={6}>
                  <RegenerateIcon color={colors.textSecondary} />
                  <Text style={[styles.actionLabel, {color: colors.textSecondary}]}>{t('chat.regenerate')}</Text>
                </TouchableOpacity>
              )}
              {!isUser && onFeedback && (
                <>
                  <TouchableOpacity
                    style={styles.actionButton}
                    onPress={() => onFeedback('up')}
                    hitSlop={6}>
                    <ThumbsUpIcon
                      color={message.feedback === 'up' ? colors.success : colors.textSecondary}
                    />
                  </TouchableOpacity>
                  <TouchableOpacity
                    style={styles.actionButton}
                    onPress={() => onFeedback('down')}
                    hitSlop={6}>
                    <ThumbsDownIcon
                      color={message.feedback === 'down' ? colors.danger : colors.textSecondary}
                    />
                  </TouchableOpacity>
                </>
              )}
              {isUser && onEdit && (
                <TouchableOpacity style={styles.actionButton} onPress={onEdit} hitSlop={6}>
                  <EditIcon color={colors.textSecondary} />
                  <Text style={[styles.actionLabel, {color: colors.textSecondary}]}>{t('chat.edit')}</Text>
                </TouchableOpacity>
              )}
            </View>
            {!isUser && message.tokensPerSecond !== undefined && message.ttftMs !== undefined && (
              <Text style={[styles.statsLabel, {color: colors.textMuted}]} numberOfLines={1}>
                {message.tokensPerSecond.toFixed(1)} tok/s · {Math.round(message.ttftMs)}ms TTFT
              </Text>
            )}
          </View>
        )}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  row: {flexDirection: 'row', marginVertical: 6, paddingHorizontal: spacing.md},
  userMaxWidth: {maxWidth: '82%'},
  assistantMaxWidth: {maxWidth: '100%'},
  aiHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  aiAvatar: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bubble: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: radius.lg,
  },
  userBubbleCorner: {borderBottomRightRadius: 4},
  // No fill, no border -- assistant replies are plain text on the
  // background, matching ChatGPT (only user messages get a bubble).
  assistantBubblePadding: {paddingHorizontal: 0},
  userText: {fontSize: 15, lineHeight: 22},
  markdownRow: {flexDirection: 'row', alignItems: 'flex-end', flexWrap: 'wrap'},
  markdownContent: {flexShrink: 1},
  cursor: {width: 8, height: 16, borderRadius: 2, marginLeft: 2, marginBottom: 3},
  image: {
    width: '100%',
    aspectRatio: 4 / 3,
    borderRadius: radius.md,
    marginBottom: spacing.xs,
  },
  actions: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    paddingHorizontal: 4,
  },
  actionsLeft: {flexDirection: 'row', alignItems: 'center', gap: spacing.md},
  actionButton: {flexDirection: 'row', alignItems: 'center', gap: 4},
  actionLabel: {fontSize: 11, fontWeight: '500'},
  statsLabel: {fontSize: 11, fontWeight: '500', marginLeft: spacing.sm},
});
